APPS-1208 - Site title wraps at certain screen sizes
UCLALibrary/sinaimanuscripts pull request #53
Opened 2021-12-07 18:00 UTC by aprigge

Connected to [APPS-1208](https://jira.library.ucla.edu/browse/APPS-1208)
Acceptance criteria:

- [x] The site title doesn't wrap at any screen size

2021-12-07 20:11 UTC, andrewbenedictwallace requested changes
I'm not able to reproduce the particular issue on my linux laptop, since it seems to be Safari-specific, but I can get the subheading to wrap by narrowing the window / increasing content size. This continues to happen after this PR.

I think maybe instead of using [`flex-wrap`](https://www.w3schools.com/cssref/css3_pr_flex-wrap.asp), we want to apply `[white-space: nobreak](https://www.w3schools.com/cssref/pr_text_white-space.asp)` to `.site-navbar__logo-title--sinai` and `.site-navbar__logo-subtitle--sinai`?

2021-12-07 22:02 UTC, jendiamond approved these changes

2021-12-07 22:07 UTC, jendiamond approved these changes

2021-12-17 21:26 UTC, andrewbenedictwallace approved these changes

2022-01-04 21:36 UTC, pghorpade approved these changes
👍

2022-01-04 21:38 UTC, merged